version: '3.8'

networks: 
  app-network: 
    driver: bridge

volumes:
  dbdata: 

services:

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    ports: 
      - "5173:5173"
    volumes:  
      - ./client/src:/usr/app/src
    tty: true 
    stdin_open: true
    environment:
      CLIENT_PORT: "5173"
      CHOKIDAR_USEPOLLING: "true"
    networks:
      - app-network
  

  backend: 
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports: 
      - "5000:5000"
    volumes:
      - ./backend/src:/usr/app/src
    environment:
      PORT: "5000"
      CHOKIDAR_USEPOLLING: "true"
    env_file:
      - ./backend/.env
    networks: 
      - app-network


  db:
    image: mongo
    restart: always
    container_name: Al-Manda-mongodb
    ports:
      - 27017:27017
    networks:
      - app-network


  # mongo:
  #   image: mongo
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
  #     MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
  #     ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongo:27017/
  #     # mongodb://root:example@mongo:27017/ 